### ISSUE TITLE
[BUG] 使用KernelSU授权root，在导出歌单时无法找到文件

### ISSUE THREAD

**Issue by xrz-cloud** [Winnie0408/LocalMusicHelper#1]
报错弹窗

```
获取数据时发生错误
错误详情：
- 数据库文件 读取失败: cp: bad '/data/data/com.netease.cloudmusic/databases/cloudmusic.db': No such file or directory
```
  
已确认 授予了完全的root权限，且MT管理器可以访问该文件。  

推测原因：申请root时没有`su --mount-master`挂载全局命名空间。  

别的：如果可以，希望能支持sui授权root。

**Comment by Winnie0408** [comment]
好耶~ 第一个Issue！
🥳🥳🥳

---

今天发布的 v1.0.2 已修复此问题。
具体解决方法是，在原cp命令前，加上 `nsenter --mount=/proc/1/ns/mnt` ，将cp命令使用全局命名空间运行，即可。
感谢反馈！
🥰🥰🥰

您说的`sui授权Root`，是指使用`Shizuku`来进行授权吗？我要研究研究，看看是否能够实现呢~
