### ISSUE TITLE
歌单来源是否能指定歌单id

### ISSUE THREAD

**Issue by gclcode** [Winnie0408/LocalMusicHelper#2]
歌单来源是否能指定歌单id
歌曲是通过第三方app下载的，本机没有安装任何的听歌软件,通过制定歌单id生成txt,直接使用saltplay听歌

**Comment by Winnie0408** [comment]
> 歌单来源是否能指定歌单id
> 歌曲是通过第三方app下载的，本机没有安装任何的听歌软件,通过制定歌单id生成txt,直接使用saltplay听歌

是指直接通过歌单ID来获取歌单数据吗？
目前是已经支持的。
需要将「歌单获取方式」选择为「在线」，然后登录对应平台的账号*，并在歌单选择页面点击右下角的「+」号即可~
(注：若不登录平台账号，只能获取到歌单中的一小部分歌曲，所以必须登录哈)

![IMG_20240410_150639.jpg](https://github.com/Winnie0408/LocalMusicHelper/assets/42741874/58a041c0-d81d-46fb-806b-a05088758713)

如果您需要的不是上述功能，麻烦您再详细描述一下您的需求呢~

**Comment by gclcode** [comment]
https://i.y.qq.com/n2/m/share/details/taoge.html?platform=11&appshare=android_qq&appversion=12050008&hosteuin=oKS5oKCPoKcqon**&id=693837784&ADTAG=wxfshare
只有这个链接

**Comment by gclcode** [comment]
QQ的 我用岸听音乐 就是 只需要QQ账号和这个 我喜欢的歌单分享链接就可以了

**Comment by gclcode** [comment]
岸听音乐 下载地址 https://www.lanzoub.com/ithNG1u0xgne

**Comment by gclcode** [comment]
而且这样登陆也有点奇怪

**Comment by gclcode** [comment]
![2471712738746_ pic](https://github.com/Winnie0408/LocalMusicHelper/assets/52744340/57903fd1-221c-4252-9bfc-7b607561d67d)
而且这样登陆也有点奇怪
