### ISSUE TITLE
已授权文件访问权限但是仍然无法读取文件

### ISSUE THREAD

**Issue by Hwenray** [Winnie0408/LocalMusicHelper#3]
在 Samsung 设备（港版 Android10）（root+shamiko，LSPosed + 酒域 - 歌词获取）环境下已授权文件访问权限但是仍然无法读取文件,有什么解决办法吗?需要提供log?但貌似翻不log所在位置...

**Comment by Hwenray** [comment]
![图片](https://github.com/user-attachments/assets/c0a2b857-69b3-4dc6-b206-d736a1c62481)

**Comment by Hwenray** [comment]
and开启导出结果后
![图片](https://github.com/user-attachments/assets/86cf6333-5123-4d53-a39c-05114c618be8)

**Comment by Hwenray** [comment]
貌似csdn上
![图片](https://github.com/user-attachments/assets/d9a6562f-9c58-441f-8cc2-c5dadbaa7053)

**Comment by Winnie0408** [comment]
感谢反馈！
我之前用Android 9的模拟器测试的时候，貌似是只测试了读取文件，写入文件没测试到，抱歉；
我有空的时候看一下这个问题，然后尝试修一下~
再次感谢反馈！
❤️❤️❤️

**Comment by Hwenray** [comment]
https://github.com/Winnie0408/LocalMusicHelper/pull/4#issue-2439567314
