### ISSUE TITLE
在未授予文件读写权限时直接使用本地转本地功能出现闪退现象

### ISSUE THREAD

**Issue by Hwenray** [Winnie0408/LocalMusicHelper#6]
经排查，此处未做文件权限授予判断

**Comment by Hwenray** [comment]
https://github.com/Winnie0408/LocalMusicHelper/pull/5#issue-2440527252

**Comment by Winnie0408** [comment]
感谢反馈！
PR将稍后处理

**Comment by Hwenray** [comment]
我才是，基本上没有什么Kotlin经验，有什么不妥的地方请指出~~~
